<?php
$Idioma = array(
//Esto te toca a ti Felipe, yo esque con HUE me lo entiendo todo pillalo
'Iniciar sesion' => 'Hue HUe HUE HUE',
'Login' => 'Hue HUe HUE HUE',
'Contraseña' => 'Hue HUe HUE HUE',
'Menu Principal' => 'Hue HUe HUE HUE',
'Menu' => 'Hue HUe HUE HUE',
'Roles' => 'Hue HUe HUE HUE',
'Usuarios' => 'Hue HUe HUE HUE',
'Funcionalidades' => 'Hue HUe HUE HUE',
'Paginas' => 'Hue HUe HUE HUE',
'Gestión de Roles' => 'Hue HUe HUE HUE',
'Gestión de Usuarios' => 'Hue HUe HUE HUE',
'Gestion de Usuario' => 'Hue HUe HUE HUE',
'Gestión de Funcionalidades' => 'Hue HUe HUE HUE',
'Gestion de Páginas' => 'Hue HUe HUE HUE',
'Gestión de Páginas' => 'Hue HUe HUE HUE',
'Rol' => 'Hue HUe HUE HUE',
'Crear rol' => 'Hue HUe HUE HUE',
'Nombre' => 'Hue HUe SONOTEEMO',
'Descripcion' => 'Hue HUe CONTAMETODOPAA',
'Eliminar' => 'Hue HUe HUE HUE',
'Crear' => 'Hue HUe HUE HUE',
'Modificar' => 'Hue HUe HUE HUE',
'Atras' => 'Hue HUe HUE HUE',
'Guardar' => 'Hue HUe HUE HUE',
'Salir' => 'Hue HUe HUE HUE',
'Modificar rol' => 'Hue HUe HUE HUE',
'Seleccionar Rol' => 'Hue HUe HUE HUE',
'Apellidos' => 'Hue HUe HUE HUE',
'Correo electronico' => 'Hue HUe HUE HUE',
'Repetir contraseña' => 'Hue HUe HUE HUE',
'Seleccionar usuario' => 'Hue HUe HUE HUE',
'Modificar contraseña' => 'Hue HUe HUE HUE',
'Modificar contraseña de usuario' => 'Hue HUe HUE HUE',
'Crear funcionalidad' => 'Hue HUe HUE HUE',
'Url' => 'Hue HUe HUE HUE',
'Seleccionar pagina' => 'Hue HUe HUE HUE',
'Ha ocurrido un error' => 'Hue HUe HUE HUE?????',
'¿Esta usted seguro/a?' => '¿Hue HUe HUE HUE?',
'Accion a confirmar' => 'Hue HUe HUE HUE',
'Crear usuario' => 'Allahu EKBER',
'Crear página' => 'Vose crea paginas every were',
'Pagina' => 'HUEHUEHUEHUEUE NOLO PILLO',
'Funcionalidad' => 'Trololo',



 
)
?>