<?php
$Idioma = array(
'salir' => 'Exit',
'ID' => 'ID',
'Email' => 'Email',
'nick' => 'nickname',
'Login' => 'Log In',
'Iniciar sesion' => 'Log In',
'Contraseña' => 'Password',
'Menu Principal' => 'Main Index',
'Menu' => 'Index',
'Roles' => 'Rol',
'Usuario' => 'User',
'Funcionalidad' => 'Feature',
'Pagina' => 'Page',
'Gestión de Roles' => 'Roles management',
'Gestión de Usuarios' => 'Users management',
'Gestión de Usuario' => 'Users management',
'Gestión de Funcionalidades' => 'Features management',
'Gestion de Páginas' => 'Pages management',
'Gestión de Páginas' => 'Pages management',
'Rol' => 'Rol',
'Crear rol' => 'Create rol',
'Nombre' => 'Nickname',
'Descripcion' => 'Description',
'Eliminar' => 'Delete',
'Crear' => 'Create',
'Modificar' => 'Edit',
'Atras' => 'Back',
'Guardar' => 'Save',
'Salir' => 'Exit',
'Modificar rol' => 'Rol edit',
'Seleccionar Rol' => 'Select rol',
'Apellidos' => 'Last name',
'Correo electronico' => 'Mail',
'Repetir contraseña' => 'Repeat password',
'Seleccionar usuario' => 'Select user',
'Modificar contraseña' => 'Edit password',
'Modificar contraseña de usuario' => 'Edit user password',
'Crear funcionalidad' => 'Create feature',
'Url' => 'Url',
'Seleccionar pagina' => 'Select page',
'Ha ocurrido un error' => 'An error has ocurred',
'¿Esta usted seguro/a?' => 'Are you sure?',
'Accion a confirmar' => 'Action to confirm',
'Crear usuario' => 'Create user',
'Repetir contraseña' => 'Repeat pass',
'permitir' => 'Grant',
'Crear página' => 'Create page',
'Seguro' => 'Sure?',
'Validar' => 'Check it',
//Lista de errores:
'1' => 'Already exist this user',
'2' => 'Passwords are not equals',
//Valido:
'Exito' => 'Sucesfull operation',
'UC' => 'Create user',

)
?>
