<?php
$Idioma = array(
'nick' => 'apodo',
'Iniciar sesion' => 'Iniciar sesion',
'Login' => 'Log In',
'Contraseña' => 'Contraseña',
'Menu Principal' => 'Menu Principal',
'Menu' => 'Menu',
'Rol' => 'Rol',
'Usuario' => 'Usuario',
'Funcionalidad' => 'Funcionalidad',
'Pagina' => 'Pagina',
'Gestión de Roles' => 'Gestion de roles',
'Gestión de Usuarios' => 'Gestion de usuarios',
'Gestión de Usuario' => 'Gestion de usuarios',
'Gestión de Funcionalidades' => 'Gestion de funcionalidades',
'Gestion de Páginas' => 'Gestion de paginas',
'Gestión de Páginas' => 'Gestion de paginas',
'Rol' => 'Rol',
'Crear rol' => 'Crear rol',
'Nombre' => 'Apodo',
'Descripcion' => 'Descripcion',
'Eliminar' => 'Eliminar',
'Crear' => 'Crear',
'Modificar' => 'Modificar',
'Atras' => 'Atras',
'Guardar' => 'Guardar',
'Salir' => 'Salir',
'Modificar rol' => 'Modificar rol',
'Seleccionar Rol' => 'Seleccionar Rol',
'Apellidos' => 'Apellidos',
'Correo electronico' => 'Correo electronico',
'Repetir contraseña' => 'Repetir contraseña',
'Seleccionar usuario' => 'Seleccionar usuario',
'Modificar contraseña' => 'Modificar contraseña',
'Modificar contraseña de usuario' => 'Modificar contraseña de usuario',
'Crear funcionalidad' => 'Crear funcionalidad',
'Url' => 'Url',
'Seleccionar pagina' => 'Seleccionar pagina',
'Ha ocurrido un error' => 'Ha ocurrido un error',
'¿Esta usted seguro/a?' => '¿Esta usted seguro/a?',
'Accion a confirmar' => 'Accion a confirmar',
'Crear usuario' => 'Crear usuario',
'Repetir contraseña' => 'Repetir contraseña',
'permitir' => 'Permitir',
'Crear página' => 'Crear página',


)
?>
